---
title: pytmac
description:
  - This is an example of how pytmac can be used to threat model your workload
  - It can handle multiple paragraphs in the description
swagger_resource_type: containers
swagger_default_network: office_network
